apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: app
      image: nginx:stable
      volumeMounts:
        - name: host
          mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /etc
        type: Directory
