apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequirenonrootreadonly
spec:
  crd:
    spec:
      names:
        kind: K8sRequireNonRootReadonly
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequirenonrootreadonly

        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          not c.securityContext.runAsNonRoot == true
          msg := sprintf("runAsNonRoot=true is required for container: %v", [c.name])
        }

        violation[{"msg": msg}] {
          c := input.review.object.spec.initContainers[_]
          not c.securityContext.runAsNonRoot == true
          msg := sprintf("runAsNonRoot=true is required for initContainer: %v", [c.name])
        }

        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          not c.securityContext.readOnlyRootFilesystem == true
          msg := sprintf("readOnlyRootFilesystem=true is required for container: %v", [c.name])
        }

        violation[{"msg": msg}] {
          c := input.review.object.spec.initContainers[_]
          not c.securityContext.readOnlyRootFilesystem == true
          msg := sprintf("readOnlyRootFilesystem=true is required for initContainer: %v", [c.name])
        }
