apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath-fixed
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: nginx:stable
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: work
          mountPath: /tmp/work
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
  volumes:
    - name: work
      emptyDir: {}
